### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by forumbaer** [fewieden/MMM-soccer#15]
One icon isn't showing in the German League (Bavaria Munich). Is there a way to refresh the icon list or something?

**Comment by fewieden** [comment]
if you can send me a svg of that logo i can fix it, problem is that the api returns one that was deleted

**Comment by forumbaer** [comment]
[Logo_FC_Bayern_München_(2002–2017).zip](https://github.com/fewieden/MMM-soccer/files/1677028/Logo_FC_Bayern_Munchen_.2002.2017.zip)

Contains the svg file.

**Comment by fewieden** [comment]
I'm sorry, it must be an accessible direct link in the web.

**Comment by forumbaer** [comment]
I hope this works:

https://upload.wikimedia.org/wikipedia/commons/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg

**Comment by fewieden** [comment]
Thanks fixed that icon and some others too
