### ISSUE TITLE
ITALY Serie A - No icons at all

### ISSUE THREAD

**Issue by SeLLeRoNe** [fewieden/MMM-soccer#18]
Hi, 
I have updated to the develop branch to use v2 APIs which are working perfectly.
The only problem I am facing is that icons are not loaded at all, also, the colored: true is referred to the icons or there should be other colors somewhere?

![image](https://user-images.githubusercontent.com/9599441/44518571-7d3fce80-a6c2-11e8-88aa-67272e876444.png)

Thanks
Andrea

**Comment by fewieden** [comment]
Hi Andrea, the v2 of the api doesn't provide icons anymore. I added a config option to hide it as it doesn't have content :/

**Comment by SeLLeRoNe** [comment]
Oh ok, I guess I missunderstood it :) Cause I saw it set to false in the config defaults (JS file) and I thought I could simply set it to true :)

It was actually a very nice thing to be honest, but I do understand it is not really up to you :)

Thanks for your help, hope to see new improvment like live match or multiple load of the same module to get different leagues and infos :)

Cheers!
Andrea
