### ISSUE TITLE
Current League "1. Bundesliga"

### ISSUE THREAD

**Issue by stefan1402** [fewieden/MMM-soccer#20]
Hello, how do I set the current league for Germany league 1?

**Comment by fewieden** [comment]
The api changed and it is no longer providing new data.

You need to use the `develop` branch, where I have a work in progress v2 of the module which supports the current standings of the `1. Bundesliga`

`git checkout develop`

**Comment by fewieden** [comment]
Did it work for you?

**Comment by stefan1402** [comment]
Sorry, I dont know what to do, 
if possible, you can also write me in German :)
-----------------------------------------------------------------
falls möglich, kannst du es mir auch auf deutsch schreiben :)

**Comment by fewieden** [comment]
1. Open a the terminal.
2. Type in `cd ~/MagicMirror/modules/MMM-soccer` to switch directory.
3. Execute `git checkout develop` to switch to the develop branch.
4. Restart your mirror.

**Comment by stefan1402** [comment]
If i do this in directory modules:
error: pathspec 'develop' did not match any file(s) known to git.

but if i switch to 
cd ~/MagicMirror/modules/MMM-soccer
"Branch develop konfiguriert zum Folgen von Remote-Branch develop von origin.
Zu neuem Branch 'develop' gewechselt"

- the code works but table is "loading"

Whats the correct League ID? i tryed leagues: {"GERMANY":452} / "BL1" but only "loading" in the table on the mirror

my config:
config: {
        api_key: "apikey",
		colored: true,
		show: 'GERMANY',
		focus_on: {"GERMANY": "FC Bayern München"},
		max_teams: 8,
		leagues: {"GERMANY":452}
    }

**Comment by fewieden** [comment]
It was my bad, but you figured out the correct directory.

The league code for germany is 2002. It's set by default so you can omit it in the config.

```
config: {
  api_key: "apikey",
  colored: true,
  show: 'GERMANY',
  focus_on: {"GERMANY": "FC Bayern München"},
  max_teams: 8,
}
```

![soccer](https://user-images.githubusercontent.com/9334168/46254397-30080700-c48f-11e8-8e06-eba8ba2b36b1.PNG)

**Comment by stefan1402** [comment]
it works!! Thank u so much :)
