### ISSUE TITLE
Odd fading behaviour

### ISSUE THREAD

**Issue by lavolp3** [fewieden/MMM-soccer#24]
Platform (Hardware/OS):
Raspberry Pi 3b+ with Raspbian Stretch
Node version:
11.4.0
MagicMirror version:
2.5.0
Module version:
latest
Description of the issue:

The fading or focus behave odd on my mirror.
Fading brightness is not like it should be. First lines are black then seemingly random brightness levels.
I tried to interprete the nunjucks part but I'm not common with that at all.

My config:

`
    {
        //disabled: true,
        module: 'MMM-soccer',
        position: 'top_left',
        config: {
            api_key: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
            show: 'GERMANY',
            colored: true,
            focus_on: {'GERMANY':'SV Werder Bremen'},
            max_teams: 7
        }
    },
`
![image](https://user-images.githubusercontent.com/20084205/50112861-a02d5a00-0240-11e9-8239-29daa870659f.png)

**Comment by fewieden** [comment]
I will take a look over the christmas holidays, do you have something in your custom.css?

**Comment by lavolp3** [comment]
I have higher color values for .dimmed .normal and .bright in my
custom..css. But nothing relating to this module.

Thanks!

Am Sa., 22. Dez. 2018 um 10:10 Uhr schrieb fewieden <
notifications@github.com>:

**Comment by lavolp3** [comment]
fixed in my fork
https://github.com/lavolp3/MMM-soccer/

in MMM-soccer.njk 
```< tr class="centered-row {% if index === boundaries.focusTeamIndex %}bright{% endif %}" style="{{loop.index | fade(boundaries.focusTeamIndex)}}" >```
```loop.index``` needs to be changed to ```index```
loop.index gives the iteration index but you need here the actual entry of the team
