### ISSUE TITLE
Error getting league table 400

### ISSUE THREAD

**Issue by EduMarron** [fewieden/MMM-soccer#27]
Platform (Hardware/OS):
Pi3 b+
Node version:

MagicMirror version:
may.2019
Module version:
may.2019
Description of the issue:
List and Icons are not showing up.

Get league table for url http://api.football-data.org/v2/competitions/undefined/standings
Error getting league table 400

![config](https://user-images.githubusercontent.com/50410532/57586101-22206700-74f1-11e9-8599-ce8be7b6da1c.JPG)
![screen](https://user-images.githubusercontent.com/50410532/57586102-22206700-74f1-11e9-93f5-4b65e0242d95.JPG)

**Comment by fewieden** [comment]
@EduMarron the country needs to be uppercase.

```js
{
    module: 'MMM-soccer',
    position: 'top_right',
    config: {
        api_key: 'XXX',
        show: 'GERMANY',
        logos: true,
        colored: true,
        max_teams: 7
    }
}
```
