### ISSUE TITLE
How to remove HEADER

### ISSUE THREAD

**Issue by thymon13** [fewieden/MMM-soccer#30]
Hello !

I would like remove the module's Header.

`   showHeader: 'false', ` doesn't work

Thank in advance

**Comment by fewieden** [comment]
hi @thymon13 your value has the type string (text inside quotes). What you need is the type boolean (true and false without quotes). By the nature of javascript, a string is always true, except it is empty.

Try `showHeader: false,`

**Comment by thymon13** [comment]
Yes Thx !
