### ISSUE TITLE
Juventus logo is not displayed

### ISSUE THREAD

**Issue by mkrause4** [fewieden/MMM-soccer#32]
Platform (Hardware/OS): Raspberry Pi 4 

Node version: v10.21.0

MagicMirror version: v2.12.0

Module version: 1.0.0

Description of the issue: I use the fork from lavolp3. Unfortunately the Juventus logo is not displayed (in the Champions League table).

**Comment by fewieden** [comment]
@Mitonix I suggest reporting the issue in the fork. If the author didn't change the logic you can just place the svg with the correct club name in the icon directory of the module to make it work.
