### ISSUE TITLE
Loading problem thank you

### ISSUE THREAD

**Issue by badjedi7238** [fewieden/MMM-soccer#38]
Platform (Hardware/OS):Rasbian full
Pi 4
MagicMirror version:2.14.0

Bonjour, j'ai suivi l'installation en sachant que je suis debutant tout fonctionne sauf le module soccer il reste sur chargement et rien ne se passe .
Est ce qu'une personne peux m'aider merci.
Je  vous mets mon fichier config.js merci
{ 
			module : "MMM-soccer" , 
			position : "lower_third",
				config : { // ajoutez vos options de configuration ici 
				leagues: "FRANCE:FL1",
				show: "FRANCE",
				focus_on: "Olympique Lyonnais"
				//max-teams: "6",
				
		}
	},

**Comment by fewieden** [comment]
@badjedi7238 sorry I can only offer support in english or german.

But from seeing your config file it looks like a similar issue to what a user on the forum reported last month https://forum.magicmirror.builders/post/86623

**Comment by fewieden** [comment]
Also, your value for leagues is wrong. Correct it would be

```
leagues: {"FRANCE": "FL1"},
```

But you also don't need to specify it at all, as it is already included in the default value.

**Comment by badjedi7238** [comment]
thanks for your help i will give it a try. i have my mirror which works for
everything else but not football? maybe a lack of space on the modules?
thank you

Tony Rainone
