### ISSUE TITLE
18. Place ar not show

### ISSUE THREAD

**Issue by redbull290** [fewieden/MMM-soccer#39]
The 18. Place in German 1. BL dosn't show - why?

Here my config

`{
		    module: 'MMM-soccer',
		    position: 'bottom_right',
		    config: {
		        // add your config options here
		        api_key: 'KEY',
		        show:"GERMANY",
		        max_teams: 6,
		        logos: true,
		        colored: true,
		        focus_on:{"GERMANY": "FC Schalke 04"}
		    }
		}`

**Comment by fewieden** [comment]
@redbull290 thank you for your report. I found the issue and fixed it in the new release that I just published. Please update the module.
